jenkins_server:
  image:
    - dockerinpractice/jenkins-ci:master
  ports:
    - 8080:8080
    - 50000:50000
    - 2222:22

jenkins_swarm_client:
  image:
    - dockerinpractice/jenkins_swarm
  ports:
    - 8081:8080
    - 2223:22
